### ISSUE TITLE
Add vCMP Guest support

### ISSUE THREAD

**Issue by erjac77** [erjac77/ansible-module-f5bigip#128]

**Comment by erjac77** [comment]
@jonozzz, This module is completed for some times now, but we hadn't the chance to release it, since we don't have VIPRION in our lab to test it. I see that you created a module for that in your "fork", so, can you have a go at that and if you find an issue, please report? Thank you for your help.

**Comment by jonozzz** [comment]
Well, first of all thanks for cleaning up my code. Yours looks better :)

Issues I found so far:
virtual_disk should be a 'str'
vlans should be a 'list'

I didn't get to test these, but noticed they're missing:

              traffic-profile [vcmp-traffic-profile-name]

              capabilities [add | delete | modify | replace-all-with] {
                  [capability Id] [ { value [integer] } ]
              }
Acceptable Id values for 'capabilities' set: appliance-mode or host-software-only-mode or stats-isolated-mode

This was tested on a 13.1.0.1 BIGIP, older versions might vary.

**Comment by erjac77** [comment]
Thanks for your help, really appreciated!

I fixed the type for virtual-disk and vlans. I also added the capabilities and traffic-profile options. I think the latter is specific to v13, since I did not see it in the v12 documentation.

Don't hesitate to open an issue if some modules you need are missing, I'd be happy to provide them (or entertain PRs).

**Comment by erjac77** [comment]
@jonozzz Do you mind if I put your name on the contributors list?

However, I'm a little confused... Is your name Jonathon Chea or Ionut Turturica?

**Comment by jonozzz** [comment]
It would make sense to add me if I actually contributed with code, in a pull request for instance. Thanks for considering it, though.
Oh, one is my alias :)

**Comment by erjac77** [comment]
You contributed by testing the vCMP Guest module, that's enough for me :)
