### ISSUE TITLE
URI should allow "super-modules" too, like 'mgmt'

### ISSUE THREAD

**Issue by jonozzz** [erjac77/ansible-module-f5bigip#130]
I'm trying to pull data from /mgmt/shared/identified-devices/config/device-info 

https://github.com/erjac77/ansible-module-f5bigip/blob/45d79cc0212ed6bd8bce2a9ac2a86332ee18bbe5/library/f5bigip_facts.py#L143

**Comment by erjac77** [comment]
@jonozzz , can you pull down a copy of the f5bigip_facts and try it to see if the recent commit I made is what you wanted?

**Comment by jonozzz** [comment]
Looks good, the namespace should also include 'cm'. But I think it shouldn't be restricted to a set of values, for example I found a bunch of odd ones in 14.0.0:

      "uri": "https://localhost/mgmt/net/self",
      "uri": "https://localhost/mgmt/subscriptions",
      "uri": "https://localhost/mgmt/net/platform",
      "uri": "https://localhost/mgmt/net/tunnel",
      "uri": "https://localhost/mgmt/net/software-hotfix",
      "uri": "https://localhost/mgmt/sys/certificate-key-file-object",
      "uri": "https://localhost/mgmt/sys/all-certificate-file-object",
      "uri": "https://localhost/mgmt/net/route-mgmt-entry",
      "uri": "https://localhost/mgmt/sys/tmm-stat",
      "uri": "https://localhost/mgmt/net/hardware-version-info",
      "uri": "https://localhost/mgmt/net/system-information",
      "uri": "https://localhost/mgmt/toc",
      "uri": "https://localhost/mgmt/net/route",
      "uri": "https://localhost/mgmt/sys/host-info-stat",
      "uri": "https://localhost/mgmt/device/big-ip/change-sources",
      "uri": "https://localhost/mgmt/net/admin-ip",
      "uri": "https://localhost/mgmt/device/common/trust/delete",
      "uri": "https://localhost/mgmt/net/interface",
      "uri": "https://localhost/mgmt/net/vlan-group",
      "uri": "https://localhost/mgmt/sys/certificate-file-object",
      "uri": "https://localhost/mgmt/sys/disk-info",
      "uri": "https://localhost/mgmt/access/file-path-manager",
      "uri": "https://localhost/mgmt/net/software-desired",
      "uri": "https://localhost/mgmt/sys/cpu-info-stat",
      "uri": "https://localhost/mgmt/net/sys-device",
      "uri": "https://localhost/mgmt/net/software-status",
      "uri": "https://localhost/mgmt/net/software-image",
      "uri": "https://localhost/mgmt/sys/apache-certificate-file-object",
      "uri": "https://localhost/mgmt/net/vlan",

**Comment by erjac77** [comment]
Ok, I removed the values restriction on the 'namespace'. Moreover, I added an 'expand_subcollections' option.

**Comment by jonozzz** [comment]
:sunglasses:
