### ISSUE TITLE
f5bigip_cm_device: "Missing required params: ['partition']"

### ISSUE THREAD

**Issue by jamie314159** [erjac77/ansible-module-f5bigip#141]
Hi,
When trying to use the f5bigip_cm_device module, regardless of what values I passed, I got the error:
> fatal: [c1-guest00 -> localhost]: FAILED! => {"changed": false, "msg": "Missing required params: ['partition']"}

Removing the line
> del self.params['partition'] 

from f5bigip_cm_device.py solved the issue.

**Comment by erjac77** [comment]
Ok, I'll look into it tomorrow. In the meantime, can you tell me the version of your BIG-IP please?

Thanks for reporting.

**Comment by erjac77** [comment]
@jamie314159 , I've just pushed a fix. Can you pull down the master branch and test it please?

**Comment by jamie314159** [comment]
I'm running 13.1.0 and 13.1.0.1. The fix looks good to me, thanks.

**Comment by erjac77** [comment]
Glad to hear that. Closing the issue. Please feel free to reopen if needed.
